language: php
php:
    - "5.4"
    - "5.5"
    - "hhvm"

matrix:
    allow_failures:
        - php: hhvm

cache:
    directories:
        - vendor

before_script:
    - composer self-update
    - composer update --prefer-source --dev

script:
    - phpunit -c app/ --testsuite PIM_Unit_Test
    - bin/phpspec run -fdot -v
