parameters:
    pim_flexibleentity.flexible_config:                               ~
    pim_flexibleentity.registry.class:                                Pim\Bundle\FlexibleEntityBundle\Manager\FlexibleManagerRegistry
    pim_flexibleentity.value_form.value_subscriber.class:             Pim\Bundle\FlexibleEntityBundle\Form\EventListener\FlexibleValueSubscriber
    pim_flexibleentity.filterAttributes.twig.extension.class:         Pim\Bundle\FlexibleEntityBundle\Twig\FilterAttributesExtension
    pim_flexibleentity.listener.set_value_class.class:                Pim\Bundle\FlexibleEntityBundle\EventListener\SetValueClassListener
    pim_flexibleentity.listener.timestampable.class:                  Pim\Bundle\FlexibleEntityBundle\EventListener\TimestampableListener
    pim_flexibleentity.listener.has_required_value.class:             Pim\Bundle\FlexibleEntityBundle\EventListener\RequiredValueListener
    pim_flexibleentity.listener.default_value.class:                  Pim\Bundle\FlexibleEntityBundle\EventListener\DefaultValueListener
    pim_flexibleentity.listener.initialize_flexible.class:            Pim\Bundle\FlexibleEntityBundle\EventListener\InitializeValuesListener
    pim_flexibleentity.listener.outdate_indexed_values.class:         Pim\Bundle\FlexibleEntityBundle\EventListener\OutdateIndexedValuesListener

services:
    pim_flexibleentity.value_form.value_subscriber:
        class: %pim_flexibleentity.value_form.value_subscriber.class%
        arguments:
            - '@form.factory'
            - '@pim_catalog.factory.attribute_type'
            - '@pim_flexibleentity.registry'

    # manager registry
    pim_flexibleentity.registry:
        class: %pim_flexibleentity.registry.class%


    # inject attributes into flexible entity
    pim_flexibleentity.listener.set_value_class:
        class: %pim_flexibleentity.listener.set_value_class.class%
        tags:
            - { name: doctrine.event_subscriber }

    # update created and updated at fields
    pim_flexibleentity.listener.timestampable:
        class: %pim_flexibleentity.listener.timestampable.class%
        tags:
            - { name: doctrine.event_subscriber }

    # ensure that required value has been set
    pim_flexibleentity.listener.has_required_value:
        class: %pim_flexibleentity.listener.has_required_value.class%
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: doctrine.event_subscriber }

    # Mark entity indexedValues as outdated once one of its value has been loaded from DB
    pim_flexibleentity.listener.outdate_indexed_values:
        class: %pim_flexibleentity.listener.outdate_indexed_values.class%
        tags:
            - { name: doctrine.event_subscriber }

    # add default value
    pim_flexibleentity.listener.listener.default_value:
        class: %pim_flexibleentity.listener.default_value.class%

    # initialize flexible entity
    pim_flexibleentity.listener.listener.initialize_values:
        class: %pim_flexibleentity.listener.initialize_flexible.class%
        tags:
            - { name: kernel.event_subscriber}

    pim_flexibleentity.filterAttributes.twig.extension:
        class: %pim_flexibleentity.filterAttributes.twig.extension.class%
        tags:
            - { name: twig.extension }
