parameters:
    pim_datagrid.product.attribute_type.pim_catalog_identifier:
        column:
            type:        product_value_field
            selector:    flexible_values
        filter:
            type:        product_value_string
            parent_type: string
        sorter:          flexible_field
    pim_datagrid.product.attribute_type.pim_catalog_text:
        column:
            type:        product_value_field
            selector:    flexible_values
        filter:
            type:        product_value_string
            parent_type: string
        sorter:          flexible_field
    pim_datagrid.product.attribute_type.pim_catalog_textarea:
        column:
            type:        product_value_field
            selector:    flexible_values
        filter:
            type:        product_value_string
            parent_type: string
        sorter:          flexible_field
    pim_datagrid.product.attribute_type.pim_catalog_simpleselect:
        column:
            type:        product_value_option
            selector:    flexible_option
        filter:
            type:        product_value_choice
            parent_type: ajax_choice
            options:
                field_options:
                    multiple: true
        sorter:          flexible_field
    pim_datagrid.product.attribute_type.pim_catalog_multiselect:
        column:
            type:        product_value_options
            selector:    flexible_options
        filter:
            type:        product_value_choice
            parent_type: ajax_choice
            options:
                field_options:
                    multiple: true
        sorter:          flexible_field
    pim_datagrid.product.attribute_type.pim_catalog_number:
        column:
            type:        product_value_field
            selector:    flexible_values
        filter:
            type:        product_value_number
            parent_type: number
        sorter:          flexible_field
    pim_datagrid.product.attribute_type.pim_catalog_boolean:
        column:
            type:          product_value_boolean
            selector:      flexible_values
            frontend_type: html
            template:      PimDataGridBundle:Property:boolean.html.twig
        filter:
            type:        product_value_boolean
            parent_type: boolean
        sorter:          flexible_field
    pim_datagrid.product.attribute_type.pim_catalog_date:
        column:
            type:          product_value_date
            selector:      flexible_values
            frontend_type: date
        filter:
            type:          product_value_date
            parent_type:   date
        sorter:            flexible_field
    pim_datagrid.product.attribute_type.pim_catalog_file:
        column:
            type:          product_value_field
            selector:      flexible_media
            frontend_type: string
        sorter:            ~
    pim_datagrid.product.attribute_type.pim_catalog_image:
        column:
            type:          product_value_image
            selector:      flexible_media
            frontend_type: html
            template:      PimDataGridBundle:Property:image.html.twig
        sorter:            ~
    pim_datagrid.product.attribute_type.pim_catalog_price_collection:
        column:
            type:        product_value_price
            selector:    flexible_price
        filter:
            type:        product_value_price
            parent_type: price
        sorter:          ~
    pim_datagrid.product.attribute_type.pim_catalog_metric:
        column:
            type:          product_value_metric
            selector:      flexible_metric
            frontend_type: html
            template:      PimDataGridBundle:Property:metric.html.twig
        filter:
            type:          product_value_metric
            parent_type:   metric
        sorter:            ~
