Pim\Bundle\CatalogBundle\Model\Association:
    type: embeddedDocument
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\MongoDBODM\AssociationRepository
    indexes:
        association_type_idx:
            options:
                unique: true
            keys:
                associationType:
    fields:
        id:
            id: true
        associationType:
            type: entity
            targetEntity: Pim\Bundle\CatalogBundle\Entity\AssociationType
        groups:
            type: entities
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Group
    referenceMany:
        products:
            targetDocument: Pim\Bundle\CatalogBundle\Model\Product
