Pim\Bundle\CatalogBundle\Model\Media:
    type: document
    collection: pim_catalog_media
    fields:
        id:
            id: true
        filename:
            type: string
        filePath:
            type: string
        originalFilename:
            type: string
        mimeType:
            type: string
