parameters:
    pim_catalog.repository.association.class:                        Pim\Bundle\CatalogBundle\Doctrine\MongoDBODM\AssociationRepository
    pim_catalog.repository.product.class:                            Pim\Bundle\CatalogBundle\Doctrine\MongoDBODM\ProductRepository
    pim_catalog.doctrine.completeness_generator.class:               Pim\Bundle\CatalogBundle\Doctrine\MongoDBODM\CompletenessGenerator
    pim_catalog.event_listener.mongodb.entities_type.class:          Pim\Bundle\CatalogBundle\EventListener\MongoDBODM\EntitiesTypeSubscriber
    pim_catalog.event_listener.mongodb.entity_type.class:            Pim\Bundle\CatalogBundle\EventListener\MongoDBODM\EntityTypeSubscriber
    pim_catalog.event_listener.mongodb.normalize_product_data.class: Pim\Bundle\CatalogBundle\EventListener\MongoDBODM\SetProductNormalizedDataSubscriber
    pim_catalog.mongodb.normalizer.family.class:                     Pim\Bundle\CatalogBundle\MongoDB\Normalizer\FamilyNormalizer
    pim_catalog.mongodb.normalizer.completeness.class:               Pim\Bundle\CatalogBundle\MongoDB\Normalizer\CompletenessNormalizer
    pim_catalog.mongodb.normalizer.product.class:                    Pim\Bundle\CatalogBundle\MongoDB\Normalizer\ProductNormalizer
    pim_catalog.mongodb.normalizer.product_value.class:              Pim\Bundle\CatalogBundle\MongoDB\Normalizer\ProductValueNormalizer
    pim_catalog.mongodb.normalizer.attribute_option.class:           Pim\Bundle\CatalogBundle\MongoDB\Normalizer\AttributeOptionNormalizer
    pim_catalog.mongodb.normalizer.product_price.class:              Pim\Bundle\CatalogBundle\MongoDB\Normalizer\ProductPriceNormalizer
    pim_catalog.mongodb.normalizer.media.class:                      Pim\Bundle\CatalogBundle\MongoDB\Normalizer\MediaNormalizer
    pim_catalog.mongodb.normalizer.datetime.class:                   Pim\Bundle\CatalogBundle\MongoDB\Normalizer\DateTimeNormalizer
    pim_catalog.doctrine.product_query_builder.class:                Pim\Bundle\CatalogBundle\Doctrine\MongoDBODM\ProductQueryBuilder
    pim_catalog.doctrine.smart_manager_registry.class:               Pim\Bundle\CatalogBundle\Doctrine\SmartManagerRegistry

services:
    pim_catalog.object_manager.product:
        alias: doctrine.odm.mongodb.document_manager

    pim_catalog.object_manager.association:
        alias: doctrine.odm.mongodb.document_manager

    pim_catalog.doctrine.completeness_generator:
        class: %pim_catalog.doctrine.completeness_generator.class%
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@pim_catalog.factory.completeness'
            - '@validator'

    pim_catalog.event_listener.mongodb.entities_type:
        class: %pim_catalog.event_listener.mongodb.entities_type.class%
        arguments:
            - '@pim_catalog.factory.referenced_collection'
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }

    pim_catalog.event_listener.mongodb.normalize_product_data:
        class: %pim_catalog.event_listener.mongodb.normalize_product_data.class%
        arguments:
            - '@pim_serializer'
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }

    pim_catalog.event_listener.mongodb.entity_type:
        class: %pim_catalog.event_listener.mongodb.entity_type.class%
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }

    # Normalizers
    pim_catalog.mongodb.normalizer.product:
        class: %pim_catalog.mongodb.normalizer.product.class%
        public: false
        tags:
            - { name: pim_serializer.normalizer }

    pim_catalog.mongodb.normalizer.product_value:
        class: %pim_catalog.mongodb.normalizer.product_value.class%
        public: false
        tags:
            - { name: pim_serializer.normalizer }

    pim_catalog.mongodb.normalizer.attribute_option:
        class: %pim_catalog.mongodb.normalizer.attribute_option.class%
        public: false
        tags:
            - { name: pim_serializer.normalizer }

    pim_catalog.mongodb.normalizer.product_price:
        class: %pim_catalog.mongodb.normalizer.product_price.class%
        public: false
        tags:
            - { name: pim_serializer.normalizer }

    pim_catalog.mongodb.normalizer.media:
        class: %pim_catalog.mongodb.normalizer.media.class%
        public: false
        tags:
            - { name: pim_serializer.normalizer }

    pim_catalog.mongodb.normalizer.family:
        class: %pim_catalog.mongodb.normalizer.family.class%
        public: false
        arguments:
            - '@pim_serializer.normalizer.label_translation'
        tags:
            - { name: pim_serializer.normalizer }

    pim_catalog.mongodb.normalizer.completeness:
        class: %pim_catalog.mongodb.normalizer.completeness.class%
        public: false
        tags:
            - { name: pim_serializer.normalizer }

    pim_catalog.mongodb.normalizer.datetime:
        class: %pim_catalog.mongodb.normalizer.datetime.class%
        public: false
        tags:
            - { name: pim_serializer.normalizer }

    pim_catalog.repository.product:
        class: %pim_catalog.repository.product.class%
        factory_service: pim_catalog.object_manager.product
        factory_method: getRepository
        arguments: [%pim_catalog.entity.product.class%]
        calls:
            - [setProductQueryBuilder, ['@pim_catalog.doctrine.product_query_builder']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            - [setCategoryClass, ['%pim_catalog.entity.category.class%']]

    pim_catalog.repository.media:
        class: %doctrine.document_repository.class%
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getRepository
        arguments: [%pim_catalog.entity.media.class%]

    pim_catalog.doctrine.smart_manager_registry:
        class: %pim_catalog.doctrine.smart_manager_registry.class%
        calls:
            - [addRegistry, ['@doctrine']]
            - [addRegistry, ['@doctrine_mongodb']]
