parameters:
    pim_catalog.repository.association.class:                      Pim\Bundle\CatalogBundle\Entity\Repository\AssociationRepository
    pim_catalog.repository.product.class:                          Pim\Bundle\CatalogBundle\Entity\Repository\ProductRepository
    pim_catalog.doctrine.completeness_generator.class:             Pim\Bundle\CatalogBundle\Doctrine\ORM\CompletenessGenerator
    pim_catalog.event_listener.orm.inject_product_reference.class: Pim\Bundle\CatalogBundle\EventListener\ORM\InjectProductReferenceSubscriber
    pim_catalog.doctrine.product_query_builder.class:              Pim\Bundle\CatalogBundle\Doctrine\ORM\ProductQueryBuilder

services:
    pim_catalog.object_manager.product:
        alias: doctrine.orm.entity_manager

    pim_catalog.object_manager.association:
        alias: doctrine.orm.entity_manager

    pim_catalog.doctrine.completeness_generator:
        class: %pim_catalog.doctrine.completeness_generator.class%
        arguments:
            - '@doctrine'
            - %pim_catalog.entity.product.class%
            - %pim_catalog.entity.product_value.class%
            - %pim_catalog.entity.attribute.class%

    pim_catalog.event_listener.orm.inject_product_reference:
        class: %pim_catalog.event_listener.orm.inject_product_reference.class%
        arguments:
            - %pim_catalog.entity.product.class%
        tags:
            - { name: doctrine.event_subscriber }

    pim_catalog.repository.product:
        class: %pim_catalog.repository.product.class%
        factory_service: pim_catalog.object_manager.product
        factory_method: getRepository
        arguments: [%pim_catalog.entity.product.class%]
        calls:
            - [setProductQueryBuilder, ['@pim_catalog.doctrine.product_query_builder']]

    pim_catalog.repository.media:
        class: %doctrine.entity_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_catalog.entity.media.class%]
